"""empty message

Revision ID: dea60c1360e1
Revises: a20ce1043f0c
Create Date: 2017-07-10 13:20:15.358867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea60c1360e1'
down_revision = 'a20ce1043f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spin', sa.Column('entries', sa.String(), nullable=True))
    op.drop_column('spin', 'players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spin', sa.Column('players', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('spin', 'entries')
    # ### end Alembic commands ###
